import htcondor

FILESYSTEM_DOMAIN = htcondor.param.get("FILESYSTEM_DOMAIN")
HMDC_BATCH_HEAD = htcondor.param.get("HMDC_BATCH_HEAD_PUB")
HMDC_INT_HEAD = htcondor.param.get("HMDC_INT_HEAD_PUB")
JOB_STATUS_IDLE = 1
JOB_STATUS_RUNNING = 2
JOB_STATUS_REMOVED = 3
JOB_STATUS_COMPLETED = 4
JOB_STATUS_HELD = 5
JOB_STATUS_SUBMIT_ERR = 6
