#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Sun Oct 25 22:13:19 2015
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from RCELaunchLaunchWindowFrame import RCELaunchLaunchWindowFrame

class RceSubmitLaunch(wx.App):
  def OnInit(self):
    wx.InitAllImageHandlers()
    LaunchWindow = RCELaunchLaunchWindowFrame(None, wx.ID_ANY, "")
    self.SetTopWindow(LaunchWindow)
    LaunchWindow.Show()
    return 1

# end of class RceSubmitLaunch

if __name__ == "__main__":
  gettext.install("RceSubmit") # replace with the appropriate catalog name

  RceSubmit = RceSubmitLaunch(0)
  RceSubmit.MainLoop()
